# Generated by Django 5.2.3 on 2025-06-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brokerage_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hidden_charges', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
            ],
        ),
    ]
